### ISSUE TITLE
V1: Security definitions not generated correctly

### ISSUE THREAD

**Issue by BigJoe01** [goadesign/goa#2147]
Hi,

I try generate swagger for my api but jwt security definitions not generated correctly into the swagger.
What doing wrong or this is an bug.

Code :+1: 

`var JWT = JWTSecurity("jwt", func() {
	Header("Authorization")

	Scope(ScopeChatUser,          "Group chat , common user access")
	Scope(ScopeChatAdmin,         "Group chat , administrator access")
	Scope(ScopeChatSuperUser,     "Group chat , publisher access")

	Scope(ScopeDebugUser,         "Debug tracker, common user access")
	Scope(ScopeDebugAdmin,        "Debug tracker, administrator access")
	Scope(ScopeDebugSuperUser,    "Debug tracker, publisher access")

	Scope(ScopeTrackingUser,      "Tracker, common user access")
	Scope(ScopeTrackingAdmin,     "Tracker, administrator access")
	Scope(ScopeTrackingSuperUser, "Tracker, publisher access")

	Scope(ScopeStorageUser,      "Storage, common user access")
	Scope(ScopeStorageAdmin,     "Storage, administrator access")
	Scope(ScopeStorageSuperUser, "Storage, publisher access")
})`
Output :
`jwt:
    description: |2-

      **Security Scopes**:
        * `char:admin`: Group chat , administrator access
        * `chat:superuser`: Group chat , publisher access
        * `chat:user`: Group chat , common user access
        * `debug:admin`: Debug tracker, administrator access
        * `debug:superuser`: Debug tracker, publisher access
        * `debug:user`: Debug tracker, common user access
        * `storage:admin`: Storage, administrator access
        * `storage:superuser`: Storage, publisher access
        * `storage:user`: Storage, common user access
        * `tracking:admin`: Tracker, administrator access
        * `tracking:superuser`: Tracker, publisher access
        * `tracking:user`: Tracker, common user access
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
`

**Comment by raphael** [comment]
Can you clarify what you expected and what differs? thank you!

**Comment by shchiv** [comment]
@raphael Hi, 
I've the same problem. 
goa version v2.0.0-wip

I have few security scopes:
var JWT = JWTSecurity("jwt", func() {
	Header("Authorization")
	Scope("scope1", "scope1 access")    
	Scope("scope2", "scope2 access") 
})

My API:
```
var _ = API("*******", func() {
	Title("*******")
	Description("*******")
	Contact(func() {
		Name("*******")
		Email("*******")
	})
	Host("*******")
	Scheme("https")
	BasePath("/api/")
	Origin("*", func() {
		Methods("GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS")
		Headers("Accept", "Content-Type", "Authorization")
		Expose("Content-Type", "Origin")
		MaxAge(600)
		Credentials()
	})
	Consumes("application/json")
	Produces("application/json")
})
```

I can generate swagger.json, but when I try to open it on https://editor.swagger.io
I got errors: 
```
Semantic error at paths./api/*****/*****.post.security.0.0
Security scope definition scope1 could not be resolved
Jump to line 53
```
and it's always warns on all lines like:
```
security:
        - jwt:
            - 'scope1'
```

How can I fixed generation of file ?

**Comment by raphael** [comment]
@shchiv first you may want to try with the latest `v2` or better yet upgrade to the latest `v3` and make sure the issue is still there. If it is please post a minimal complete design that we can use to repro or better if you want to submit a PR take a look at the [OpenAPI generator code](https://github.com/goadesign/goa/blob/v3/http/codegen/openapi.go). This code simply serializes an [openapi.V2 struct](https://github.com/goadesign/goa/blob/v3/http/codegen/openapi/openapi_v2.go).
